services:
  docmost:
    build:
      context: .
      dockerfile: Dockerfile
    #image: docmost/docmost:latest
    container_name: mydocmost
    depends_on:
      - db
      - valkey
    env_file:
      - .env
    ports:
      - ${APP_HOST_PORT:-3010}:3000
    restart: unless-stopped
    volumes:
      - ./data/docmost:/app/data/storage

  db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT:-25432}:5432
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9.1-alpine3.23
    command: ["valkey-server", "--appendonly", "yes", "--maxmemory-policy", "noeviction"]
    restart: unless-stopped
    volumes:
      - ./data/valkey:/data
